version: '3.9'

services:
  db:
    image: postgres:15
    container_name: barter_platform_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: barter_platform_web
    command: bash entrypoint.sh
    volumes:
      - .:/barter_platform
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DEBUG=1
    restart: always

volumes:
  postgres_data:
