# Generated by Django 5.2.1 on 2025-05-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=10),
        ),
    ]
